AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws

  Sample SAM Template for aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java8
    MemorySize: 512
    Environment:
      Variables:
        dbEndpoint: http://192.168.56.1:8000/
        dbRegion: us-east-1

Resources:
  InsertItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: dboperations.Insert::handleRequest
      Environment:
        Variables:
          Category: Fashion
          Title: T-Shirt
          Price: 150
          Stock: 100
      Events:
        InsertItem:
          Type: Api
          Properties:
            Path: /insert
            Method: post
  SelectItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: dboperations.Select::handleRequest
      Environment:
        Variables:
          Category: Fashion   #Tech or Fashion
      Events:
        SelectItem:
          Type: Api
          Properties:
            Path: /select
            Method: get
  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: dboperations.Update::handleRequest
      Environment:
        Variables:
          Category: Fashion
          Title: T-Shirt
          NewPrice: 100
          NewStock: 100
      Events:
        UpdateItem:
          Type: Api
          Properties:
            Path: /update
            Method: put

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
